version: "3"

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
    # TODO: envから取得する
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: password
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      # - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    command: --port 3306
    tty: true
  api:
    depends_on:
      - db
    container_name: "api"
    build: ./docker
    ports:
      - "8080:8080"
    volumes:
      - ./api:/usr/src/server